# Generated by Django 5.0.2 on 2024-03-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
                ('phone', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
