# Generated by Django 5.0.2 on 2024-03-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickting', '0003_showtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='address',
            field=models.TextField(default='temporary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cinema',
            name='poster',
            field=models.ImageField(null=True, upload_to='movie_posters/', verbose_name='poster'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='temporery', upload_to='movie_posters/', verbose_name='poster'),
            preserve_default=False,
        ),
    ]
