# Generated by Django 5.0.2 on 2024-03-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickting', '0004_cinema_address_cinema_poster_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='movie_posters/', verbose_name='poster'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, upload_to='movie_posters/', verbose_name='poster'),
        ),
    ]
