# Generated by Django 5.0.2 on 2024-03-24 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('tickting', '0005_alter_cinema_poster_alter_movie_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(verbose_name='seat number')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='order time')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.profile', verbose_name='customer')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickting.showtime', verbose_name='showtime')),
            ],
        ),
    ]
