# Generated by Django 5.0.2 on 2024-03-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickting', '0006_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='order_time',
            field=models.DateTimeField(verbose_name='order time'),
        ),
    ]
