# Generated by Django 5.0.2 on 2024-03-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickting', '0007_alter_ticket_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='order_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='order time'),
        ),
    ]
