# Generated by Django 5.0.2 on 2024-03-24 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='mobile number')),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'male'), (2, 'female')], null=True, verbose_name='gender')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='birthday')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('profileimage', models.ImageField(blank=True, null=True, upload_to='users/profile_image', verbose_name='image')),
                ('balance', models.IntegerField(default=0, verbose_name='balance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='profile')),
            ],
        ),
    ]
